<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            // O‘quvchilar
            ['guard_name' => 'view_students', 'slug' => 'view_students', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchilar ro‘yxatini ko‘rish'],
            ['guard_name' => 'create_students', 'slug' => 'create_students', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchilarni qo‘shish'],
            ['guard_name' => 'edit_students', 'slug' => 'edit_students', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchilarni tahrirlash'],
            ['guard_name' => 'delete_students', 'slug' => 'delete_students', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchilarni o‘chirish'],
            ['guard_name' => 'view_parents', 'slug' => 'view_parents', 'group' => 'O‘quvchilar', 'description' => 'Ota-onalarni ko‘rish'],
            ['guard_name' => 'create_parents', 'slug' => 'create_parents', 'group' => 'O‘quvchilar', 'description' => 'Ota-onalarni qo‘shish'],
            ['guard_name' => 'edit_parents', 'slug' => 'edit_parents', 'group' => 'O‘quvchilar', 'description' => 'Ota-onalarni tahrirlash'],
            ['guard_name' => 'delete_parents', 'slug' => 'delete_parents', 'group' => 'O‘quvchilar', 'description' => 'Ota-onalarni o‘chirish'],
            ['guard_name' => 'view_student_status', 'slug' => 'view_student_status', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchi holatini ko‘rish'],
            ['guard_name' => 'create_student_status', 'slug' => 'create_student_status', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchi holatini qo‘shish'],
            ['guard_name' => 'edit_student_status', 'slug' => 'edit_student_status', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchi holatini tahrirlash'],
            ['guard_name' => 'delete_student_status', 'slug' => 'delete_student_status', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchi holatini o‘chirish'],
            ['guard_name' => 'view_student_login', 'slug' => 'view_student_login', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchining kirish ma‘lumotlarini ko‘rish'],
            ['guard_name' => 'create_student_login', 'slug' => 'create_student_login', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchining kirish ma‘lumotlarini qo‘shish'],
            ['guard_name' => 'edit_student_login', 'slug' => 'edit_student_login', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchining kirish ma‘lumotlarini tahrirlash'],
            ['guard_name' => 'delete_student_login', 'slug' => 'delete_student_login', 'group' => 'O‘quvchilar', 'description' => 'O‘quvchining kirish ma‘lumotlarini o‘chirish'],
            // To‘lovlar
            ['guard_name' => 'view_payments', 'slug' => 'view_payments', 'group' => 'To‘lovlar', 'description' => 'To‘lovlarni ko‘rish'],
            ['guard_name' => 'create_payments', 'slug' => 'create_payments', 'group' => 'To‘lovlar', 'description' => 'To‘lovlarni qo‘shish'],
            ['guard_name' => 'edit_payments', 'slug' => 'edit_payments', 'group' => 'To‘lovlar', 'description' => 'To‘lovlarni tahrirlash'],
            ['guard_name' => 'delete_payments', 'slug' => 'delete_payments', 'group' => 'To‘lovlar', 'description' => 'To‘lovlarni o‘chirish'],
            ['guard_name' => 'view_balance_sheet', 'slug' => 'view_balance_sheet', 'group' => 'To‘lovlar', 'description' => 'Hisob-kitob varaqasini ko‘rish'],
            ['guard_name' => 'create_balance_sheet', 'slug' => 'create_balance_sheet', 'group' => 'To‘lovlar', 'description' => 'Hisob-kitob varaqasini qo‘shish'],
            ['guard_name' => 'edit_balance_sheet', 'slug' => 'edit_balance_sheet', 'group' => 'To‘lovlar', 'description' => 'Hisob-kitob varaqasini tahrirlash'],
            ['guard_name' => 'delete_balance_sheet', 'slug' => 'delete_balance_sheet', 'group' => 'To‘lovlar', 'description' => 'Hisob-kitob varaqasini o‘chirish'],
            // Chiqimlar
            ['guard_name' => 'view_expenses', 'slug' => 'view_expenses', 'group' => 'Chiqimlar', 'description' => 'Chiqimlarni ko‘rish'],
            ['guard_name' => 'create_expenses', 'slug' => 'create_expenses', 'group' => 'Chiqimlar', 'description' => 'Chiqimlarni qo‘shish'],
            ['guard_name' => 'edit_expenses', 'slug' => 'edit_expenses', 'group' => 'Chiqimlar', 'description' => 'Chiqimlarni tahrirlash'],
            ['guard_name' => 'delete_expenses', 'slug' => 'delete_expenses', 'group' => 'Chiqimlar', 'description' => 'Chiqimlarni o‘chirish'],
            ['guard_name' => 'view_expense_categories', 'slug' => 'view_expense_categories', 'group' => 'Chiqimlar', 'description' => 'Chiqim kategoriyalarini ko‘rish'],
            ['guard_name' => 'create_expense_categories', 'slug' => 'create_expense_categories', 'group' => 'Chiqimlar', 'description' => 'Chiqim kategoriyalarini qo‘shish'],
            ['guard_name' => 'edit_expense_categories', 'slug' => 'edit_expense_categories', 'group' => 'Chiqimlar', 'description' => 'Chiqim kategoriyalarini tahrirlash'],
            ['guard_name' => 'delete_expense_categories', 'slug' => 'delete_expense_categories', 'group' => 'Chiqimlar', 'description' => 'Chiqim kategoriyalarini o‘chirish'],
            // Marketing
            ['guard_name' => 'view_notifications', 'slug' => 'view_notifications', 'group' => 'Marketing', 'description' => 'Bildirishnomalarni ko‘rish'],
            ['guard_name' => 'create_notifications', 'slug' => 'create_notifications', 'group' => 'Marketing', 'description' => 'Bildirishnomalarni qo‘shish'],
            ['guard_name' => 'edit_notifications', 'slug' => 'edit_notifications', 'group' => 'Marketing', 'description' => 'Bildirishnomalarni tahrirlash'],
            ['guard_name' => 'delete_notifications', 'slug' => 'delete_notifications', 'group' => 'Marketing', 'description' => 'Bildirishnomalarni o‘chirish'],
            ['guard_name' => 'view_sms_sending', 'slug' => 'view_sms_sending', 'group' => 'Marketing', 'description' => 'SMS yuborishni ko‘rish'],
            ['guard_name' => 'create_sms_sending', 'slug' => 'create_sms_sending', 'group' => 'Marketing', 'description' => 'SMS yuborishni qo‘shish'],
            ['guard_name' => 'edit_sms_sending', 'slug' => 'edit_sms_sending', 'group' => 'Marketing', 'description' => 'SMS yuborishni tahrirlash'],
            ['guard_name' => 'delete_sms_sending', 'slug' => 'delete_sms_sending', 'group' => 'Marketing', 'description' => 'SMS yuborishni o‘chirish'],
            ['guard_name' => 'view_sms_log', 'slug' => 'view_sms_log', 'group' => 'Marketing', 'description' => 'SMS jurnalini ko‘rish'],
            ['guard_name' => 'create_sms_log', 'slug' => 'create_sms_log', 'group' => 'Marketing', 'description' => 'SMS jurnalini qo‘shish'],
            ['guard_name' => 'edit_sms_log', 'slug' => 'edit_sms_log', 'group' => 'Marketing', 'description' => 'SMS jurnalini tahrirlash'],
            ['guard_name' => 'delete_sms_log', 'slug' => 'delete_sms_log', 'group' => 'Marketing', 'description' => 'SMS jurnalini o‘chirish'],
            // Imtihon
            ['guard_name' => 'view_exams', 'slug' => 'view_exams', 'group' => 'Imtihon', 'description' => 'Imtihonlarni ko‘rish'],
            ['guard_name' => 'create_exams', 'slug' => 'create_exams', 'group' => 'Imtihon', 'description' => 'Imtihonlarni qo‘shish'],
            ['guard_name' => 'edit_exams', 'slug' => 'edit_exams', 'group' => 'Imtihon', 'description' => 'Imtihonlarni tahrirlash'],
            ['guard_name' => 'delete_exams', 'slug' => 'delete_exams', 'group' => 'Imtihon', 'description' => 'Imtihonlarni o‘chirish'],
            ['guard_name' => 'view_grade_entry', 'slug' => 'view_grade_entry', 'group' => 'Imtihon', 'description' => 'Ballarni qo‘yishni ko‘rish'],
            ['guard_name' => 'create_grade_entry', 'slug' => 'create_grade_entry', 'group' => 'Imtihon', 'description' => 'Ballarni qo‘yishni qo‘shish'],
            ['guard_name' => 'edit_grade_entry', 'slug' => 'edit_grade_entry', 'group' => 'Imtihon', 'description' => 'Ballarni qo‘yishni tahrirlash'],
            ['guard_name' => 'delete_grade_entry', 'slug' => 'delete_grade_entry', 'group' => 'Imtihon', 'description' => 'Ballarni qo‘yishni o‘chirish'],
            ['guard_name' => 'view_grading_system', 'slug' => 'view_grading_system', 'group' => 'Imtihon', 'description' => 'Baholash tizimini ko‘rish'],
            ['guard_name' => 'create_grading_system', 'slug' => 'create_grading_system', 'group' => 'Imtihon', 'description' => 'Baholash tizimini qo‘shish'],
            ['guard_name' => 'edit_grading_system', 'slug' => 'edit_grading_system', 'group' => 'Imtihon', 'description' => 'Baholash tizimini tahrirlash'],
            ['guard_name' => 'delete_grading_system', 'slug' => 'delete_grading_system', 'group' => 'Imtihon', 'description' => 'Baholash tizimini o‘chirish'],
            ['guard_name' => 'view_exam_schedule', 'slug' => 'view_exam_schedule', 'group' => 'Imtihon', 'description' => 'Imtihonlar jadvalini ko‘rish'],
            ['guard_name' => 'create_exam_schedule', 'slug' => 'create_exam_schedule', 'group' => 'Imtihon', 'description' => 'Imtihonlar jadvalini qo‘shish'],
            ['guard_name' => 'edit_exam_schedule', 'slug' => 'edit_exam_schedule', 'group' => 'Imtihon', 'description' => 'Imtihonlar jadvalini tahrirlash'],
            ['guard_name' => 'delete_exam_schedule', 'slug' => 'delete_exam_schedule', 'group' => 'Imtihon', 'description' => 'Imtihonlar jadvalini o‘chirish'],
            // Ta‘lim
            ['guard_name' => 'view_timetable', 'slug' => 'view_timetable', 'group' => 'Ta‘lim', 'description' => 'Darslar jadvalini ko‘rish'],
            ['guard_name' => 'create_timetable', 'slug' => 'create_timetable', 'group' => 'Ta‘lim', 'description' => 'Darslar jadvalini qo‘shish'],
            ['guard_name' => 'edit_timetable', 'slug' => 'edit_timetable', 'group' => 'Ta‘lim', 'description' => 'Darslar jadvalini tahrirlash'],
            ['guard_name' => 'delete_timetable', 'slug' => 'delete_timetable', 'group' => 'Ta‘lim', 'description' => 'Darslar jadvalini o‘chirish'],
            ['guard_name' => 'view_branches', 'slug' => 'view_branches', 'group' => 'Ta‘lim', 'description' => 'Filiallarini ko‘rish'],
            ['guard_name' => 'create_branches', 'slug' => 'create_branches', 'group' => 'Ta‘lim', 'description' => 'Filiallarini qo‘shish'],
            ['guard_name' => 'edit_branches', 'slug' => 'edit_branches', 'group' => 'Ta‘lim', 'description' => 'Filiallarini tahrirlash'],
            ['guard_name' => 'delete_branches', 'slug' => 'delete_branches', 'group' => 'Ta‘lim', 'description' => 'Filiallarini o‘chirish'],
            ['guard_name' => 'view_groups', 'slug' => 'view_groups', 'group' => 'Ta‘lim', 'description' => 'Guruhlarni ko‘rish'],
            ['guard_name' => 'create_groups', 'slug' => 'create_groups', 'group' => 'Ta‘lim', 'description' => 'Guruhlarni qo‘shish'],
            ['guard_name' => 'edit_groups', 'slug' => 'edit_groups', 'group' => 'Ta‘lim', 'description' => 'Guruhlarni tahrirlash'],
            ['guard_name' => 'delete_groups', 'slug' => 'delete_groups', 'group' => 'Ta‘lim', 'description' => 'Guruhlarni o‘chirish'],
            ['guard_name' => 'view_assign_group_leader', 'slug' => 'view_assign_group_leader', 'group' => 'Ta‘lim', 'description' => 'Guruh rahbarini belgilashni ko‘rish'],
            ['guard_name' => 'create_assign_group_leader', 'slug' => 'create_assign_group_leader', 'group' => 'Ta‘lim', 'description' => 'Guruh rahbarini belgilashni qo‘shish'],
            ['guard_name' => 'edit_assign_group_leader', 'slug' => 'edit_assign_group_leader', 'group' => 'Ta‘lim', 'description' => 'Guruh rahbarini belgilashni tahrirlash'],
            ['guard_name' => 'delete_assign_group_leader', 'slug' => 'delete_assign_group_leader', 'group' => 'Ta‘lim', 'description' => 'Guruh rahbarini belgilashni o‘chirish'],
            // Kadrlar bo‘limi
            ['guard_name' => 'view_employees', 'slug' => 'view_employees', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlarni ko‘rish'],
            ['guard_name' => 'create_employees', 'slug' => 'create_employees', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlarni qo‘shish'],
            ['guard_name' => 'edit_employees', 'slug' => 'edit_employees', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlarni tahrirlash'],
            ['guard_name' => 'delete_employees', 'slug' => 'delete_employees', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlarni o‘chirish'],
            ['guard_name' => 'view_employee_termination', 'slug' => 'view_employee_termination', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimni ishdan bo‘shatishni ko‘rish'],
            ['guard_name' => 'create_employee_termination', 'slug' => 'create_employee_termination', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimni ishdan bo‘shatishni qo‘shish'],
            ['guard_name' => 'edit_employee_termination', 'slug' => 'edit_employee_termination', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimni ishdan bo‘shatishni tahrirlash'],
            ['guard_name' => 'delete_employee_termination', 'slug' => 'delete_employee_termination', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimni ishdan bo‘shatishni o‘chirish'],
            ['guard_name' => 'view_employee_attendance', 'slug' => 'view_employee_attendance', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlar davomatini ko‘rish'],
            ['guard_name' => 'create_employee_attendance', 'slug' => 'create_employee_attendance', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlar davomatini qo‘shish'],
            ['guard_name' => 'edit_employee_attendance', 'slug' => 'edit_employee_attendance', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlar davomatini tahrirlash'],
            ['guard_name' => 'delete_employee_attendance', 'slug' => 'delete_employee_attendance', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlar davomatini o‘chirish'],
            ['guard_name' => 'view_employee_attendance_report', 'slug' => 'view_employee_attendance_report', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlar davomati hisobotini ko‘rish'],
            ['guard_name' => 'create_employee_attendance_report', 'slug' => 'create_employee_attendance_report', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlar davomati hisobotini qo‘shish'],
            ['guard_name' => 'edit_employee_attendance_report', 'slug' => 'edit_employee_attendance_report', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlar davomati hisobotini tahrirlash'],
            ['guard_name' => 'delete_employee_attendance_report', 'slug' => 'delete_employee_attendance_report', 'group' => 'Kadrlar bo‘limi', 'description' => 'Xodimlar davomati hisobotini o‘chirish'],
            ['guard_name' => 'view_salary', 'slug' => 'view_salary', 'group' => 'Kadrlar bo‘limi', 'description' => 'Ish haqini ko‘rish'],
            ['guard_name' => 'create_salary', 'slug' => 'create_salary', 'group' => 'Kadrlar bo‘limi', 'description' => 'Ish haqini qo‘shish'],
            ['guard_name' => 'edit_salary', 'slug' => 'edit_salary', 'group' => 'Kadrlar bo‘limi', 'description' => 'Ish haqini tahrirlash'],
            ['guard_name' => 'delete_salary', 'slug' => 'delete_salary', 'group' => 'Kadrlar bo‘limi', 'description' => 'Ish haqini o‘chirish'],
            ['guard_name' => 'view_salary_report', 'slug' => 'view_salary_report', 'group' => 'Kadrlar bo‘limi', 'description' => 'Ish-haqi hisobotini ko‘rish'],
            ['guard_name' => 'create_salary_report', 'slug' => 'create_salary_report', 'group' => 'Kadrlar bo‘limi', 'description' => 'Ish-haqi hisobotini qo‘shish'],
            ['guard_name' => 'edit_salary_report', 'slug' => 'edit_salary_report', 'group' => 'Kadrlar bo‘limi', 'description' => 'Ish-haqi hisobotini tahrirlash'],
            ['guard_name' => 'delete_salary_report', 'slug' => 'delete_salary_report', 'group' => 'Kadrlar bo‘limi', 'description' => 'Ish-haqi hisobotini o‘chirish'],
            ['guard_name' => 'view_departments', 'slug' => 'view_departments', 'group' => 'Kadrlar bo‘limi', 'description' => 'Bo‘limlarni ko‘rish'],
            ['guard_name' => 'create_departments', 'slug' => 'create_departments', 'group' => 'Kadrlar bo‘limi', 'description' => 'Bo‘limlarni qo‘shish'],
            ['guard_name' => 'edit_departments', 'slug' => 'edit_departments', 'group' => 'Kadrlar bo‘limi', 'description' => 'Bo‘limlarni tahrirlash'],
            ['guard_name' => 'delete_departments', 'slug' => 'delete_departments', 'group' => 'Kadrlar bo‘limi', 'description' => 'Bo‘limlarni o‘chirish'],
            ['guard_name' => 'view_positions', 'slug' => 'view_positions', 'group' => 'Kadrlar bo‘limi', 'description' => 'Lavozimlarni ko‘rish'],
            ['guard_name' => 'create_positions', 'slug' => 'create_positions', 'group' => 'Kadrlar bo‘limi', 'description' => 'Lavozimlarni qo‘shish'],
            ['guard_name' => 'edit_positions', 'slug' => 'edit_positions', 'group' => 'Kadrlar bo‘limi', 'description' => 'Lavozimlarni tahrirlash'],
            ['guard_name' => 'delete_positions', 'slug' => 'delete_positions', 'group' => 'Kadrlar bo‘limi', 'description' => 'Lavozimlarni o‘chirish'],
            ['guard_name' => 'view_view_user_profiles', 'slug' => 'view_view_user_profiles', 'group' => 'Kadrlar bo‘limi', 'description' => 'Foydalanuvchilar profilini ko‘rish'],
            ['guard_name' => 'create_view_user_profiles', 'slug' => 'create_view_user_profiles', 'group' => 'Kadrlar bo‘limi', 'description' => 'Foydalanuvchilar profilini qo‘shish'],
            ['guard_name' => 'edit_view_user_profiles', 'slug' => 'edit_view_user_profiles', 'group' => 'Kadrlar bo‘limi', 'description' => 'Foydalanuvchilar profilini tahrirlash'],
            ['guard_name' => 'delete_view_user_profiles', 'slug' => 'delete_view_user_profiles', 'group' => 'Kadrlar bo‘limi', 'description' => 'Foydalanuvchilar profilini o‘chirish'],
            // Tizimni sozlash
            ['guard_name' => 'view_languages', 'slug' => 'view_languages', 'group' => 'Tizimni sozlash', 'description' => 'Tillarni ko‘rish'],
            ['guard_name' => 'create_languages', 'slug' => 'create_languages', 'group' => 'Tizimni sozlash', 'description' => 'Tillarni qo‘shish'],
            ['guard_name' => 'edit_languages', 'slug' => 'edit_languages', 'group' => 'Tizimni sozlash', 'description' => 'Tillarni tahrirlash'],
            ['guard_name' => 'delete_languages', 'slug' => 'delete_languages', 'group' => 'Tizimni sozlash', 'description' => 'Tillarni o‘chirish'],
            ['guard_name' => 'view_general_settings', 'slug' => 'view_general_settings', 'group' => 'Tizimni sozlash', 'description' => 'Umumiy sozlamalarni ko‘rish'],
            ['guard_name' => 'create_general_settings', 'slug' => 'create_general_settings', 'group' => 'Tizimni sozlash', 'description' => 'Umumiy sozlamalarni qo‘shish'],
            ['guard_name' => 'edit_general_settings', 'slug' => 'edit_general_settings', 'group' => 'Tizimni sozlash', 'description' => 'Umumiy sozlamalarni tahrirlash'],
            ['guard_name' => 'delete_general_settings', 'slug' => 'delete_general_settings', 'group' => 'Tizimni sozlash', 'description' => 'Umumiy sozlamalarni o‘chirish'],
            ['guard_name' => 'view_billing_settings', 'slug' => 'view_billing_settings', 'group' => 'Tizimni sozlash', 'description' => 'Billing sozlamalarini ko‘rish'],
            ['guard_name' => 'create_billing_settings', 'slug' => 'create_billing_settings', 'group' => 'Tizimni sozlash', 'description' => 'Billing sozlamalarini qo‘shish'],
            ['guard_name' => 'edit_billing_settings', 'slug' => 'edit_billing_settings', 'group' => 'Tizimni sozlash', 'description' => 'Billing sozlamalarini tahrirlash'],
            ['guard_name' => 'delete_billing_settings', 'slug' => 'delete_billing_settings', 'group' => 'Tizimni sozlash', 'description' => 'Billing sozlamalarini o‘chirish'],
            ['guard_name' => 'view_roles_permissions', 'slug' => 'view_roles_permissions', 'group' => 'Tizimni sozlash', 'description' => 'Rollar va ruxsatlarni ko‘rish'],
            ['guard_name' => 'create_roles_permissions', 'slug' => 'create_roles_permissions', 'group' => 'Tizimni sozlash', 'description' => 'Rollar va ruxsatlarni qo‘shish'],
            ['guard_name' => 'edit_roles_permissions', 'slug' => 'edit_roles_permissions', 'group' => 'Tizimni sozlash', 'description' => 'Rollar va ruxsatlarni tahrirlash'],
            ['guard_name' => 'delete_roles_permissions', 'slug' => 'delete_roles_permissions', 'group' => 'Tizimni sozlash', 'description' => 'Rollar va ruxsatlarni o‘chirish'],
            ['guard_name' => 'view_backup', 'slug' => 'view_backup', 'group' => 'Tizimni sozlash', 'description' => 'Rezerv nusxalashni ko‘rish'],
            ['guard_name' => 'create_backup', 'slug' => 'create_backup', 'group' => 'Tizimni sozlash', 'description' => 'Rezerv nusxalashni qo‘shish'],
            ['guard_name' => 'edit_backup', 'slug' => 'edit_backup', 'group' => 'Tizimni sozlash', 'description' => 'Rezerv nusxalashni tahrirlash'],
            ['guard_name' => 'delete_backup', 'slug' => 'delete_backup', 'group' => 'Tizimni sozlash', 'description' => 'Rezerv nusxalashni o‘chirish'],
            ['guard_name' => 'view_restore', 'slug' => 'view_restore', 'group' => 'Tizimni sozlash', 'description' => 'Tiklashni ko‘rish'],
            ['guard_name' => 'create_restore', 'slug' => 'create_restore', 'group' => 'Tizimni sozlash', 'description' => 'Tiklashni qo‘shish'],
            ['guard_name' => 'edit_restore', 'slug' => 'edit_restore', 'group' => 'Tizimni sozlash', 'description' => 'Tiklashni tahrirlash'],
            ['guard_name' => 'delete_restore', 'slug' => 'delete_restore', 'group' => 'Tizimni sozlash', 'description' => 'Tiklashni o‘chirish'],
            // Konsol va vidjetlar
            ['guard_name' => 'view_change_session', 'slug' => 'view_change_session', 'group' => 'Konsol va vidjetlar', 'description' => 'Sessiyani o‘zgartirishni ko‘rish'],
            ['guard_name' => 'create_change_session', 'slug' => 'create_change_session', 'group' => 'Konsol va vidjetlar', 'description' => 'Sessiyani o‘zgartirishni qo‘shish'],
            ['guard_name' => 'edit_change_session', 'slug' => 'edit_change_session', 'group' => 'Konsol va vidjetlar', 'description' => 'Sessiyani o‘zgartirishni tahrirlash'],
            ['guard_name' => 'delete_change_session', 'slug' => 'delete_change_session', 'group' => 'Konsol va vidjetlar', 'description' => 'Sessiyani o‘zgartirishni o‘chirish'],
            ['guard_name' => 'view_monthly_income_expense_chart', 'slug' => 'view_monthly_income_expense_chart', 'group' => 'Konsol va vidjetlar', 'description' => 'Daromad va chiqimning oylik diagrammasini ko‘rish'],
            ['guard_name' => 'create_monthly_income_expense_chart', 'slug' => 'create_monthly_income_expense_chart', 'group' => 'Konsol va vidjetlar', 'description' => 'Daromad va chiqimning oylik diagrammasini qo‘shish'],
            ['guard_name' => 'edit_monthly_income_expense_chart', 'slug' => 'edit_monthly_income_expense_chart', 'group' => 'Konsol va vidjetlar', 'description' => 'Daromad va chiqimning oylik diagrammasini tahrirlash'],
            ['guard_name' => 'delete_monthly_income_expense_chart', 'slug' => 'delete_monthly_income_expense_chart', 'group' => 'Konsol va vidjetlar', 'description' => 'Daromad va chiqimning oylik diagrammasini o‘chirish'],
            ['guard_name' => 'view_yearly_income_expense_chart', 'slug' => 'view_yearly_income_expense_chart', 'group' => 'Konsol va vidjetlar', 'description' => 'Daromad va chiqimning yillik diagrammasini ko‘rish'],
            ['guard_name' => 'create_yearly_income_expense_chart', 'slug' => 'create_yearly_income_expense_chart', 'group' => 'Konsol va vidjetlar', 'description' => 'Daromad va chiqimning yillik diagrammasini qo‘shish'],
            ['guard_name' => 'edit_yearly_income_expense_chart', 'slug' => 'edit_yearly_income_expense_chart', 'group' => 'Konsol va vidjetlar', 'description' => 'Daromad va chiqimning yillik diagrammasini tahrirlash'],
            ['guard_name' => 'delete_yearly_income_expense_chart', 'slug' => 'delete_yearly_income_expense_chart', 'group' => 'Konsol va vidjetlar', 'description' => 'Daromad va chiqimning yillik diagrammasini o‘chirish'],
            ['guard_name' => 'view_fund_collection_widget', 'slug' => 'view_fund_collection_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Mablag‘ yig‘ish vidjetini ko‘rish'],
            ['guard_name' => 'create_fund_collection_widget', 'slug' => 'create_fund_collection_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Mablag‘ yig‘ish vidjetini qo‘shish'],
            ['guard_name' => 'edit_fund_collection_widget', 'slug' => 'edit_fund_collection_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Mablag‘ yig‘ish vidjetini tahrirlash'],
            ['guard_name' => 'delete_fund_collection_widget', 'slug' => 'delete_fund_collection_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Mablag‘ yig‘ish vidjetini o‘chirish'],
            ['guard_name' => 'view_expense_widget', 'slug' => 'view_expense_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Chiqimlar vidjetini ko‘rish'],
            ['guard_name' => 'create_expense_widget', 'slug' => 'create_expense_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Chiqimlar vidjetini qo‘shish'],
            ['guard_name' => 'edit_expense_widget', 'slug' => 'edit_expense_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Chiqimlar vidjetini tahrirlash'],
            ['guard_name' => 'delete_expense_widget', 'slug' => 'delete_expense_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Chiqimlar vidjetini o‘chirish'],
            ['guard_name' => 'view_student_count_widget', 'slug' => 'view_student_count_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'O‘quvchilar soni vidjetini ko‘rish'],
            ['guard_name' => 'create_student_count_widget', 'slug' => 'create_student_count_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'O‘quvchilar soni vidjetini qo‘shish'],
            ['guard_name' => 'edit_student_count_widget', 'slug' => 'edit_student_count_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'O‘quvchilar soni vidjetini tahrirlash'],
            ['guard_name' => 'delete_student_count_widget', 'slug' => 'delete_student_count_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'O‘quvchilar soni vidjetini o‘chirish'],
            ['guard_name' => 'view_employee_count_widget', 'slug' => 'view_employee_count_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Xodimlar soni vidjetini ko‘rish'],
            ['guard_name' => 'create_employee_count_widget', 'slug' => 'create_employee_count_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Xodimlar soni vidjetini qo‘shish'],
            ['guard_name' => 'edit_employee_count_widget', 'slug' => 'edit_employee_count_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Xodimlar soni vidjetini tahrirlash'],
            ['guard_name' => 'delete_employee_count_widget', 'slug' => 'delete_employee_count_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Xodimlar soni vidjetini o‘chirish'],
            ['guard_name' => 'view_birthday_widget', 'slug' => 'view_birthday_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Tug‘ilgan kun vidjetini ko‘rish'],
            ['guard_name' => 'create_birthday_widget', 'slug' => 'create_birthday_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Tug‘ilgan kun vidjetini qo‘shish'],
            ['guard_name' => 'edit_birthday_widget', 'slug' => 'edit_birthday_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Tug‘ilgan kun vidjetini tahrirlash'],
            ['guard_name' => 'delete_birthday_widget', 'slug' => 'delete_birthday_widget', 'group' => 'Konsol va vidjetlar', 'description' => 'Tug‘ilgan kun vidjetini o‘chirish'],
        ];

        // Faqat mavjud bo‘lmagan ruxsatlarni qo‘shish
        foreach ($permissions as $permission) {
            if (!DB::table('permissions')->where('guard_name', $permission['guard_name'])->exists()) {
                DB::table('permissions')->insert($permission);
            }
        }
    }
}